//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerManager.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the idle power plan specified in settings as
        ///&quot;{0}&quot;, make sure it matches the name of the balanced plan 
        ///(or whatever plan you want to use) that you see in 
        ///Windows power plan settings exactly.
        ///
        ///Once you have found the correct name, update the 
        ///contents of the config file located at:
        ///{1}.
        /// </summary>
        internal static string Program_Error_IdleSchemeNull {
            get {
                return ResourceManager.GetString("Program_Error_IdleSchemeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find specified power plan.
        /// </summary>
        internal static string Program_Error_IdleSchemeNull_Title {
            get {
                return ResourceManager.GetString("Program_Error_IdleSchemeNull_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the performance power plan specified in settings as
        ///&quot;{0}&quot;, make sure it matches the name of the high performance plan 
        ///that you see in Windows power plan settings exactly.
        ///
        ///Once you have found the correct name, update the contents of the config file located at:
        ///{1}.
        /// </summary>
        internal static string Program_Error_PerformanceSchemeNull {
            get {
                return ResourceManager.GetString("Program_Error_PerformanceSchemeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find specified power plan.
        /// </summary>
        internal static string Program_Error_PerformanceSchemeNull_Title {
            get {
                return ResourceManager.GetString("Program_Error_PerformanceSchemeNull_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csgo,bf4,TslGame,bf5,bf1,bf2042,dayz,Rust.
        /// </summary>
        internal static string Settings_Default_Application {
            get {
                return ResourceManager.GetString("Settings_Default_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 381b4222-f694-41f0-9685-ff5bb260df2e.
        /// </summary>
        internal static string Settings_Default_IdleGuid {
            get {
                return ResourceManager.GetString("Settings_Default_IdleGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced.
        /// </summary>
        internal static string Settings_Default_IdleName {
            get {
                return ResourceManager.GetString("Settings_Default_IdleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c.
        /// </summary>
        internal static string Settings_Default_PerformanceGuid {
            get {
                return ResourceManager.GetString("Settings_Default_PerformanceGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High performance.
        /// </summary>
        internal static string Settings_Default_PerformanceName {
            get {
                return ResourceManager.GetString("Settings_Default_PerformanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open config file in editor. Try opening the following file manually: 
        ///.
        /// </summary>
        internal static string Settings_OpenInEditor_Error {
            get {
                return ResourceManager.GetString("Settings_OpenInEditor_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open editor.
        /// </summary>
        internal static string Settings_OpenInEditor_Error_Title {
            get {
                return ResourceManager.GetString("Settings_OpenInEditor_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found no valid settings, wrote template ones to file..
        /// </summary>
        internal static string Settings_Setup_NotFound {
            get {
                return ResourceManager.GetString("Settings_Setup_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this menu.
        /// </summary>
        internal static string TrayIcon_CreateContextMenu_CloseMenuItem {
            get {
                return ResourceManager.GetString("TrayIcon_CreateContextMenu_CloseMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string TrayIcon_CreateContextMenu_ExitItem {
            get {
                return ResourceManager.GetString("TrayIcon_CreateContextMenu_ExitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerManager.
        /// </summary>
        internal static string TrayIcon_CreateContextMenu_MenuTitle {
            get {
                return ResourceManager.GetString("TrayIcon_CreateContextMenu_MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open config file.
        /// </summary>
        internal static string TrayIcon_CreateContextMenu_OpenConfigItem {
            get {
                return ResourceManager.GetString("TrayIcon_CreateContextMenu_OpenConfigItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart PowerManager.
        /// </summary>
        internal static string TrayIcon_CreateContextMenu_RestartPowerManagerItem {
            get {
                return ResourceManager.GetString("TrayIcon_CreateContextMenu_RestartPowerManagerItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active power plan: {0}.
        /// </summary>
        internal static string TrayIcon_UpdateActivePowerPlan_ActivePlanItemText {
            get {
                return ResourceManager.GetString("TrayIcon_UpdateActivePowerPlan_ActivePlanItemText", resourceCulture);
            }
        }
    }
}
